# Generated by Django 4.2.3 on 2023-07-25 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_online_shop', '0002_alter_onlineshop_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnlineShop',
        ),
    ]
